/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function runCommand(command: string, cwd: string, args: Array<string>): string
export function removeDirectory(directory: string): void
export function readLine(content: string): string
